import os
import time
print('                           :@@@@@@@@@@@')                                                                      
print('                           @@@@@@@@@@@@@@@')                                                                    
print('                          @@@@@@@@@@@@@@@@@@')                                                                  
print('                         @@@@@@@@@  @@@@@@@@@')                                                                 
print('        @@@@@@@@&  @@M  G@@@@@@@@   s@@@@@@@@ ;@@@@@@@5   r@@@@@@@    @@@@@@@r')                                
print('        @@@@@@@@;@@@@@  @@@@@@@@@   .@@@@@@@@  @@@@@@@@   @@@@@@@@   r@@@@@@@')                                 
print('        @@@@@@@@@@@@@@  @@@@@@@@@   .@@@@@@@@  .@@@@@@@   @@@@@@@@   @@@@@@@@')                                 
print('        @@@@@@@@@@@@@@  @@@@@@@@@   .@@@@@@@@  S@@@@@@@   @@@@@@@@   @@@@@@@@')                                 
print('        @@@@@@@@@@@@@@  @@@@@@@@@   .@@@@@@@@   @@@@@@@  G@@@@@@@@G S@@@@@@@.')                                 
print('        @@@@@@@@@@@@@@  @@@@@@@@@   .@@@@@@@@   @@@@@@@r @@@@@@@@@@ @@@@@@@@r')                                 
print('        @@@@@@@@@@      @@@@@@@@@   .@@@@@@@@   @@@@@@@H @@@@@@@@@@ @@@@@@@@')                                  
print('        @@@@@@@@@       @@@@@@@@@   .@@@@@@@@   M@@@@@@@ @@@@@@@@@@ @@@@@@@@')                                  
print('        @@@@@@@@@       @@@@@@@@@   .@@@@@@@@   s@@@@@@@ @@@@@@@@@@ @@@@@@@G')                                  
print('        @@@@@@@@M       @@@@@@@@@   .@@@@@@@@    @@@@@@@@@@@@@@@@@@@@@@@@@@')                                   
print('        @@@@@@@@B       @@@@@@@@@   .@@@@@@@@    @@@@@@@@@@@@@@@@@@@@@@@@@@')                                   
print('        @@@@@@@@B       @@@@@@@@@   .@@@@@@@@    @@@@@@@@@@@@G @@@@@@@@@@@@')                                   
print('        @@@@@@@@B       @@@@@@@@@   .@@@@@@@@    B@@@@@@@@@@@  @@@@@@@@@@@@')                                   
print('        @@@@@@@@B       M@@@@@@@@   S@@@@@@@@    ,@@@@@@@@@@@  @@@@@@@@@@@G')                                   
print('        @@@@@@@@B        @@@@@@@@G  @@@@@@@@@     @@@@@@@@@@@  A@@@@@@@@@@,')                                   
print('        @@@@@@@@B         @@@@@@@@@@@@@@@@@@      @@@@@@@@@@B   @@@@@@@@@@')                                    
print('        @@@@@@@@B          @@@@@@@@@@@@@@@,       @@@@@@@@@@    @@@@@@@@@@')                                    
print('        @@@@@@@@B            i@@@@@@@@@@;         H@@@@@@@@@    @@@@@@@@@@')                                    
print('')                                                                                                              
print('')                                                                                                              
print('                                                                             @@@@@@@@@@@@@@@@@@@@@@@@@@')       
print('')
print('Программа "Взлом кода" v0.1')
print('Запуск...')
time.sleep(60)
print('----------')
print('Успешно!')
time.sleep(1)
print('----------')
cmd = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd == ('analyze'):
    print('# ^ I ! $ H V )')
    time.sleep(0.5)
    print('L * ( X B @ ! !')
    time.sleep(0.5)
    print('" > , < X F Q @')
    time.sleep(0.5)
    print('; H J & $ @ C Q')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd1 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd1 == ('analyze'):
    print('# ^ I ! $ H V 0')
    time.sleep(0.6)
    print('L * ( X B @ ! 0')
    time.sleep(0.6)
    print('" > , < X F Q 0')
    time.sleep(0.6)
    print('; H J & $ @ C 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd2 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd2 == ('analyze'):
    print('# ^ I ! $ H 0 0')
    time.sleep(0.7)
    print('L * ( X B @ 0 0')
    time.sleep(0.7)
    print('" > , < X F 0 0')
    time.sleep(0.7)
    print('; H J & $ @ 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd3 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd3 == ('analyze'):
    print('# ^ I ! $ 0 0 0')
    time.sleep(0.8)
    print('L * ( X B 0 0 0')
    time.sleep(0.8)
    print('" > , < X 0 0 0')
    time.sleep(0.8)
    print('; H J & $ 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd4 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd4 == ('analyze'):
    print('# ^ I ! 0 0 0 0')
    time.sleep(0.9)
    print('L * ( X 0 0 0 0')
    time.sleep(0.9)
    print('" > , < 0 0 0 0')
    time.sleep(0.9)
    print('; H J & 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd5 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd5 == ('analyze'):
    print('# ^ I 0 0 0 0 0')
    time.sleep(1.0)
    print('L * ( 0 0 0 0 0')
    time.sleep(1.0)
    print('" > , 0 0 0 0 0')
    time.sleep(1.0)
    print('; H J 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd6 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd6 == ('analyze'):
    print('# ^ 0 0 0 0 0 0')
    time.sleep(1.1)
    print('L * 0 0 0 0 0 0')
    time.sleep(1.1)
    print('" > 0 0 0 0 0 0')
    time.sleep(1.1)
    print('; H 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd7 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd7 == ('analyze'):
    print('# 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('L 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('" 4 0 0 0 0 0 0')
    time.sleep(1.2)
    print('; 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd8 = str(input('Введи команду "analyze" чтобы расшифровать 1 цифру кода: '))
if cmd8 == ('analyze'):
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 4 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
time.sleep(2)
print('------------------------------')
print('Первая цифра разблокирована!')
time.sleep(2)
print('------------------------------')
cmd9 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd9 == ('analyze'):
    print('# ^ I ! $ H V )')
    time.sleep(0.5)
    print('L * ( X B @ ! !')
    time.sleep(0.5)
    print('" > , < X F Q @')
    time.sleep(0.5)
    print('; H J & $ @ C Q')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd10 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd10 == ('analyze'):
    print('# ^ I ! $ H V 9')
    time.sleep(0.6)
    print('L * ( X B @ ! 0')
    time.sleep(0.6)
    print('" > , < X F Q 0')
    time.sleep(0.6)
    print('; H J & $ @ C 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd11 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd11 == ('analyze'):
    print('# ^ I ! $ H 0 9')
    time.sleep(0.7)
    print('L * ( X B @ 0 0')
    time.sleep(0.7)
    print('" > , < X F 0 0')
    time.sleep(0.7)
    print('; H J & $ @ 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd12 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd12 == ('analyze'):
    print('# ^ I ! $ 0 0 9')
    time.sleep(0.8)
    print('L * ( X B 0 0 0')
    time.sleep(0.8)
    print('" > , < X 0 0 0')
    time.sleep(0.8)
    print('; H J & $ 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd13 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd13 == ('analyze'):
    print('# ^ I ! 0 0 0 9')
    time.sleep(0.9)
    print('L * ( X 0 0 0 0')
    time.sleep(0.9)
    print('" > , < 0 0 0 0')
    time.sleep(0.9)
    print('; H J & 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
print('------------------------------')
vir1 = str(input('Обнаружен вирус, найдена глушительная антенна, найдите антенну в Зимовье, там есть код дешифровщика и напишите его сюда: '))
if vir1 == ('930917832540019862310101302764401259091347201321762444'):
    print('Обработка...')
    time.sleep(10)
    print('Глушительная антенна отключена.')
    time.sleep(2)
    print('Взлом продолжается.')
else:
    print('Обработка...')
    time.sleep(10)
    print('Ключ применён неудачно.')
    os.system(pause)
print('------------------------------')
cmd14 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd14 == ('analyze'):
    print('# ^ I 0 0 0 0 9')
    time.sleep(1.0)
    print('L * ( 0 0 0 0 0')
    time.sleep(1.0)
    print('" > , 0 0 0 0 0')
    time.sleep(1.0)
    print('; H J 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd15 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd15 == ('analyze'):
    print('# ^ 0 0 0 0 0 9')
    time.sleep(1.1)
    print('L * 0 0 0 0 0 0')
    time.sleep(1.1)
    print('" > 0 0 0 0 0 0')
    time.sleep(1.1)
    print('; H 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd16 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd16 == ('analyze'):
    print('# 0 0 0 0 0 0 9')
    time.sleep(1.2)
    print('L 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('" 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('; 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd17 = str(input('Введи команду "analyze" чтобы расшифровать 2 цифру кода: '))
if cmd17 == ('analyze'):
    print('0 0 0 0 0 0 0 9')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
time.sleep(2)
print('------------------------------')
print('Вторая цифра разблокирована!')
time.sleep(2)
print('------------------------------')
cmd18 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd18 == ('analyze'):
    print('# ^ I ! $ H V )')
    time.sleep(0.5)
    print('L * ( X B @ ! !')
    time.sleep(0.5)
    print('" > , < X F Q @')
    time.sleep(0.5)
    print('; H J & $ @ C Q')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd19 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd19 == ('analyze'):
    print('# ^ I ! $ H V 0')
    time.sleep(0.6)
    print('L * ( X B @ ! 0')
    time.sleep(0.6)
    print('" > , < X F Q 0')
    time.sleep(0.6)
    print('; H J & $ @ C 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd20 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd20 == ('analyze'):
    print('# ^ I ! $ H 0 0')
    time.sleep(0.7)
    print('L * ( X B @ 0 0')
    time.sleep(0.7)
    print('" > , < X F 0 0')
    time.sleep(0.7)
    print('; H J & $ @ 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd21 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd21 == ('analyze'):
    print('# ^ I ! $ 0 0 0')
    time.sleep(0.8)
    print('L * ( X B 0 0 0')
    time.sleep(0.8)
    print('" > , < X 0 0 0')
    time.sleep(0.8)
    print('; H J & $ 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd22 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd22 == ('analyze'):
    print('# ^ I ! 0 0 0 0')
    time.sleep(0.9)
    print('L * ( X 0 0 0 0')
    time.sleep(0.9)
    print('" > , < 0 0 0 0')
    time.sleep(0.9)
    print('; H J & 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd23 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd23 == ('analyze'):
    print('# ^ I 0 0 0 0 0')
    time.sleep(1.0)
    print('L * ( 0 0 0 0 0')
    time.sleep(1.0)
    print('" > , 0 0 0 0 0')
    time.sleep(1.0)
    print('; H J 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd24 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd24 == ('analyze'):
    print('# ^ 0 0 0 0 0 0')
    time.sleep(1.1)
    print('L * 0 0 0 0 0 0')
    time.sleep(1.1)
    print('" > 0 0 0 0 0 0')
    time.sleep(1.1)
    print('; H 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd25 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd25 == ('analyze'):
    print('# 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('L 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('" 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('; 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd26 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd26 == ('analyze'):
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
time.sleep(2)
print('------------------------------')
print('Третья цифра разблокирована!')
time.sleep(2)
print('------------------------------')
cmd27 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd27 == ('analyze'):
    print('# ^ I ! $ H V )')
    time.sleep(0.5)
    print('L * ( X B @ ! !')
    time.sleep(0.5)
    print('" > , < X F Q @')
    time.sleep(0.5)
    print('; H J & $ @ C Q')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd28 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd28 == ('analyze'):
    print('# ^ I ! $ H V 0')
    time.sleep(0.6)
    print('L * ( X B @ ! 0')
    time.sleep(0.6)
    print('" > , < X F Q 0')
    time.sleep(0.6)
    print('; H J & $ @ C 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd29 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd29 == ('analyze'):
    print('# ^ I ! $ H 0 0')
    time.sleep(0.7)
    print('L * ( X B @ 0 0')
    time.sleep(0.7)
    print('" > , < X F 0 0')
    time.sleep(0.7)
    print('; H J & $ @ 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd30 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd30 == ('analyze'):
    print('# ^ I ! $ 0 0 0')
    time.sleep(0.8)
    print('L * ( X B 0 0 0')
    time.sleep(0.8)
    print('" > , < X 0 0 0')
    time.sleep(0.8)
    print('; H J & $ 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd31 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd31 == ('analyze'):
    print('# ^ I ! 0 0 0 0')
    time.sleep(0.9)
    print('L * ( X 0 0 0 0')
    time.sleep(0.9)
    print('" > , < 0 0 0 0')
    time.sleep(0.9)
    print('; H J & 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd32 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd32 == ('analyze'):
    print('# ^ I 0 0 0 0 0')
    time.sleep(1.0)
    print('L * ( 0 0 0 0 0')
    time.sleep(1.0)
    print('" > , 0 0 0 0 0')
    time.sleep(1.0)
    print('; H J 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd33 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd33 == ('analyze'):
    print('# ^ 0 0 0 0 0 0')
    time.sleep(1.1)
    print('L * 0 0 0 0 0 0')
    time.sleep(1.1)
    print('" > 0 0 0 0 0 0')
    time.sleep(1.1)
    print('; H 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
cmd34 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd34 == ('analyze'):
    print('# 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('L 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('" 0 0 0 0 0 0 0')
    time.sleep(1.2)
    print('; 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
print('------------------------------')
vir2 = str(input('Обнаружен вирус, найдена глушительная антенна, найдите антенну на Веранде, там есть код дешифровщика и напишите его сюда: '))
if vir2 == ('1670234905327689214040021367510252398765432101734733713372287113540'):
    print('Обработка...')
    time.sleep(10)
    print('Глушительная антенна отключена.')
    time.sleep(2)
    print('Взлом продолжается.')
else:
    print('Обработка...')
    time.sleep(10)
    print('Ключ применён неудачно.')
    os.system(pause)
print('------------------------------')
cmd35 = str(input('Введи команду "analyze" чтобы расшифровать 3 цифру кода: '))
if cmd35 == ('analyze'):
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('0 0 0 0 0 0 0 0')
    time.sleep(1.3)
    print('7 0 0 0 0 0 0 0')
else:
    print('Неизвестная команда.')
    os.system(pause)
time.sleep(2)
print('------------------------------')
print('Четвёртая цифра разблокирована!')
time.sleep(2)
print('------------------------------')
time.sleep(2)
print('Программа завершила работу!')
os.system(pause)
